# Generated by Django 6.0.6 on 2026-07-14 12:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='date')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='total orders')),
                ('cancelled_orders_count', models.PositiveIntegerField(default=0, verbose_name='cancelled orders count')),
                ('refunded_orders_count', models.PositiveIntegerField(default=0, verbose_name='refunded orders count')),
                ('total_gmv_pkr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total order value before returns and cancellations.', max_digits=14, verbose_name='gross merchandise value (PKR)')),
                ('net_revenue_pkr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GMV minus refunds and discounts.', max_digits=14, verbose_name='net revenue (PKR)')),
                ('avg_order_value_pkr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='average order value (PKR)')),
                ('cod_orders_count', models.PositiveIntegerField(default=0, verbose_name='COD orders count')),
                ('prepaid_orders_count', models.PositiveIntegerField(default=0, verbose_name='prepaid orders count')),
                ('total_discount_given_pkr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total discount given (PKR)')),
                ('rto_orders_count', models.PositiveIntegerField(default=0, help_text='Orders returned to origin on this date.', verbose_name='RTO orders count')),
                ('rto_losses_pkr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Wasted shipping fees due to RTO.', max_digits=12, verbose_name='RTO losses (PKR)')),
            ],
            options={
                'verbose_name': 'daily sales snapshot',
                'verbose_name_plural': 'daily sales snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CourierPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.CharField(choices=[('postex', 'PostEx'), ('tcs', 'TCS Courier'), ('leopards', 'Leopards Courier'), ('trax', 'Trax Logistics'), ('instaworld', 'InstaWorld'), ('movex', 'Movex'), ('self_delivery', 'In-House Fleet')], max_length=20, verbose_name='courier partner')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='city')),
                ('month_year', models.DateField(db_index=True, help_text='First day of the month this metric covers. e.g. 2026-07-01 represents July 2026.', verbose_name='month')),
                ('total_assigned', models.PositiveIntegerField(default=0, verbose_name='total assigned')),
                ('delivered_successfully', models.PositiveIntegerField(default=0, verbose_name='delivered successfully')),
                ('rto_count', models.PositiveIntegerField(default=0, verbose_name='RTO count')),
                ('avg_delivery_time_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='average delivery time (hours)')),
            ],
            options={
                'verbose_name': 'courier performance metric',
                'verbose_name_plural': 'courier performance metrics',
                'ordering': ['-month_year'],
                'indexes': [models.Index(fields=['city', 'courier'], name='analytics_c_city_d6c932_idx'), models.Index(fields=['courier', 'month_year'], name='analytics_c_courier_4979b9_idx')],
                'constraints': [models.UniqueConstraint(fields=('courier', 'city', 'month_year'), name='unique_courier_city_month')],
            },
        ),
    ]
