# Generated by Django 6.0.6 on 2026-07-14 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('wrong_item', 'Wrong Item Delivered'), ('damaged', 'Item Damaged / Defective'), ('not_described', 'Not as Described'), ('changed_mind', 'Changed Mind'), ('other', 'Other')], max_length=20, verbose_name='reason')),
                ('reason_detail', models.TextField(blank=True, default='', help_text='Customer explanation in their own words.', verbose_name='reason detail')),
                ('resolution_requested', models.CharField(choices=[('refund', 'Refund to Original Payment Method'), ('exchange', 'Exchange for Same Item'), ('store_credit', 'Store Credit')], default='refund', max_length=15, verbose_name='resolution requested')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved — Awaiting Item'), ('rejected', 'Rejected'), ('item_received', 'Item Received at Warehouse'), ('refund_initiated', 'Refund Initiated'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='Required when status=REJECTED.', verbose_name='rejection reason')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='item received at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='orders.order', verbose_name='order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='orders.orderitem', verbose_name='order item')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_returns', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by admin')),
            ],
            options={
                'verbose_name': 'return request',
                'verbose_name_plural': 'return requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='returns/%Y/%m/', verbose_name='photo')),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='caption')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='returns.returnrequest', verbose_name='return request')),
            ],
            options={
                'verbose_name': 'return item photo',
                'verbose_name_plural': 'return item photos',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['order', 'status'], name='returns_ret_order_i_7316d9_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status', 'created_at'], name='returns_ret_status_51132c_idx'),
        ),
    ]
