# Generated by Django 6.0.6 on 2026-06-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='activitylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='author',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
