# Generated by Django 6.0.6 on 2026-07-14 11:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_lowstockalert_productspecification_stockreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(help_text='ML model confidence score. Range: 0.0 (low) to 1.0 (high).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='confidence score')),
                ('model_version', models.CharField(help_text="e.g. 'collab-filtering-v2.1'", max_length=50, verbose_name='model version')),
                ('is_clicked', models.BooleanField(default=False, help_text='True when customer clicks this recommendation.', verbose_name='is clicked')),
                ('recommended_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='products.product', verbose_name='recommended product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'personalized recommendation',
                'verbose_name_plural': 'personalized recommendations',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['user', 'model_version', 'score'], name='recomendati_user_id_5b963e_idx'), models.Index(fields=['recommended_product', 'score'], name='recomendati_recomme_764219_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'recommended_product', 'model_version'), name='unique_recommendation_per_user_product_model')],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='session key')),
                ('query', models.CharField(db_index=True, max_length=255, verbose_name='search query')),
                ('results_count', models.PositiveIntegerField(default=0, help_text='Number of products returned. 0 = zero results search.', verbose_name='results count')),
                ('filters_applied', models.JSONField(blank=True, help_text="Active filters at search time. e.g. {'category': 'brakes', 'bike': 'cd70'}", null=True, verbose_name='filters applied')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='searched at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'search log',
                'verbose_name_plural': 'search logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query', 'created_at'], name='recomendati_query_25d56e_idx'), models.Index(fields=['results_count', 'created_at'], name='recomendati_results_ad8e7c_idx'), models.Index(fields=['user', 'created_at'], name='recomendati_user_id_a1f435_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='For anonymous visitor tracking before login.', max_length=40, null=True, verbose_name='session key')),
                ('event_type', models.CharField(choices=[('view_product', 'Viewed Product Page'), ('add_to_cart', 'Added to Cart'), ('remove_from_cart', 'Removed from Cart'), ('add_to_wishlist', 'Added to Wishlist'), ('purchased', 'Purchased Product'), ('search_query', 'Executed Search')], db_index=True, max_length=20, verbose_name='event type')),
                ('search_query', models.CharField(blank=True, help_text='Only set for SEARCH_QUERY events.', max_length=255, null=True, verbose_name='search query')),
                ('metadata', models.JSONField(blank=True, help_text="Additional event context. e.g. {'time_spent_seconds': 45, 'device': 'mobile'}", null=True, verbose_name='metadata')),
                ('product', models.ForeignKey(blank=True, help_text='Null for SEARCH_QUERY events.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_logs', to='products.product', verbose_name='product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user interaction log',
                'verbose_name_plural': 'user interaction logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'event_type'], name='recomendati_product_21757c_idx'), models.Index(fields=['user', 'event_type', 'created_at'], name='recomendati_user_id_0994aa_idx'), models.Index(fields=['event_type', 'created_at'], name='recomendati_event_t_36fe9b_idx')],
            },
        ),
    ]
