# Generated by Django 6.0.6 on 2026-07-14 12:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_type', models.CharField(choices=[('original', 'Original Dispatch'), ('reshipment', 'Replacement / Reshipment'), ('return', 'Reverse Return Pickup')], default='original', max_length=15, verbose_name='shipment type')),
                ('courier', models.CharField(choices=[('postex', 'PostEx'), ('tcs', 'TCS Courier'), ('leopards', 'Leopards Courier'), ('trax', 'Trax Logistics'), ('instaworld', 'InstaWorld'), ('movex', 'Movex'), ('self_delivery', 'In-House Fleet')], max_length=20, verbose_name='courier partner')),
                ('tracking_number', models.CharField(db_index=True, help_text='Airway Bill number assigned by courier.', max_length=100, unique=True, verbose_name='tracking number (AWB)')),
                ('status', models.CharField(choices=[('label_created', 'Label Created / Booked'), ('picked_up', 'Picked Up by Courier'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('rto_in_transit', 'Returned to Origin (In Transit)'), ('rto_delivered', 'Returned to Seller Warehouse'), ('lost', 'Lost in Transit')], db_index=True, default='label_created', max_length=30, verbose_name='status')),
                ('is_cod', models.BooleanField(default=True, verbose_name='is COD')),
                ('cod_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount courier collects from customer on delivery.', max_digits=10, verbose_name='COD amount (PKR)')),
                ('shipping_cost_pkr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost charged by courier to seller.', max_digits=8, verbose_name='shipping cost (PKR)')),
                ('destination_city', models.CharField(db_index=True, help_text='Denormalized from OrderShippingAddress for courier API routing. Set at shipment creation — never updated after.', max_length=100, verbose_name='destination city')),
                ('weight_kg', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5, verbose_name='weight (kg)')),
                ('estimated_delivery_date', models.DateField(blank=True, null=True, verbose_name='estimated delivery date')),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='actual delivery date')),
                ('raw_courier_response', models.JSONField(blank=True, help_text='Raw API response from courier at label creation.', null=True, verbose_name='raw courier response')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'shipment',
                'verbose_name_plural': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourierSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.CharField(choices=[('postex', 'PostEx'), ('tcs', 'TCS Courier'), ('leopards', 'Leopards Courier'), ('trax', 'Trax Logistics'), ('instaworld', 'InstaWorld'), ('movex', 'Movex'), ('self_delivery', 'In-House Fleet')], max_length=20, verbose_name='courier partner')),
                ('settlement_reference', models.CharField(help_text='Bank transfer ID or courier remittance advice number.', max_length=100, unique=True, verbose_name='settlement reference')),
                ('total_cod_collected', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='total COD collected (PKR)')),
                ('total_shipping_deducted', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='total shipping deducted (PKR)')),
                ('net_payout_received', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='net payout received (PKR)')),
                ('payout_date', models.DateField(verbose_name='payout date')),
                ('is_reconciled', models.BooleanField(default=False, help_text='True after finance team verifies against bank statement.', verbose_name='is reconciled')),
                ('shipments_included', models.ManyToManyField(related_name='settlements', to='logistics.shipment', verbose_name='shipments included')),
            ],
            options={
                'verbose_name': 'courier settlement',
                'verbose_name_plural': 'courier settlements',
                'ordering': ['-payout_date'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=30, verbose_name='previous status')),
                ('to_status', models.CharField(max_length=30, verbose_name='new status')),
                ('source', models.CharField(choices=[('webhook', 'Courier Webhook'), ('manual', 'Manual Admin Update'), ('system', 'System Automated')], default='webhook', max_length=10, verbose_name='update source')),
                ('raw_webhook_data', models.JSONField(blank=True, null=True, verbose_name='raw webhook data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='logged at')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='logistics.shipment', verbose_name='shipment')),
            ],
            options={
                'verbose_name': 'shipment status log',
                'verbose_name_plural': 'shipment status logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['courier', 'status'], name='logistics_s_courier_e0e08a_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['destination_city', 'status'], name='logistics_s_destina_c8d715_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', 'created_at'], name='logistics_s_status_f7bb9f_idx'),
        ),
        migrations.AddIndex(
            model_name='couriersettlement',
            index=models.Index(fields=['courier', 'payout_date'], name='logistics_c_courier_e2dbe5_idx'),
        ),
        migrations.AddIndex(
            model_name='couriersettlement',
            index=models.Index(fields=['is_reconciled', 'payout_date'], name='logistics_c_is_reco_c70924_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentstatuslog',
            index=models.Index(fields=['shipment', 'created_at'], name='logistics_s_shipmen_7df405_idx'),
        ),
    ]
