# Generated by Django 6.0.6 on 2026-07-14 12:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_phone', models.CharField(blank=True, help_text='+923XXXXXXXXX for SMS/WhatsApp channels.', max_length=15, null=True, verbose_name='recipient phone')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='recipient email')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp Business API'), ('sms', 'SMS (Local Gateway)'), ('email', 'Email'), ('in_app', 'In-App Push / Bell Icon')], max_length=20, verbose_name='channel')),
                ('notification_type', models.CharField(choices=[('cod_verification', 'COD Order Verification'), ('order_placed', 'Order Placed'), ('order_shipped', 'Order Shipped (AWB Attached)'), ('out_for_delivery', 'Rider Out For Delivery'), ('promotional', 'Marketing / Discount Alert'), ('system_alert', 'System / Security Alert')], max_length=30, verbose_name='notification type')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('context_data', models.JSONField(blank=True, help_text="Template variables for message rendering. e.g. {'order_number': 'MBP-2026-000001', 'awb': 'TCS-99'}", null=True, verbose_name='context data')),
                ('is_sent', models.BooleanField(default=False, help_text='True after at least one successful delivery attempt.', verbose_name='is sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('is_read', models.BooleanField(blank=True, default=None, help_text='Only applicable for IN_APP channel. Null for SMS/Email/WhatsApp — not applicable.', null=True, verbose_name='is read')),
                ('failure_reason', models.TextField(blank=True, default='', help_text='Last failure reason — full history in NotificationDeliveryAttempt.', verbose_name='failure reason')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.order', verbose_name='related order')),
                ('user', models.ForeignKey(blank=True, help_text='SET_NULL — notification history preserved after deletion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient user')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome', models.CharField(choices=[('success', 'Delivered Successfully'), ('failed', 'Delivery Failed')], max_length=10, verbose_name='outcome')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='attempted at')),
                ('failure_reason', models.TextField(blank=True, default='', verbose_name='failure reason')),
                ('gateway_response', models.JSONField(blank=True, help_text='Raw response from SMS/WhatsApp/Email gateway.', null=True, verbose_name='gateway response')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='notifications.notification', verbose_name='notification')),
            ],
            options={
                'verbose_name': 'notification delivery attempt',
                'verbose_name_plural': 'notification delivery attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCODVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Pakistani phone number. Format: +923001234567 or 03001234567', regex='^\\+?92\\d{10}$|^0\\d{10}$')], verbose_name='phone number')),
                ('meta_message_id', models.CharField(blank=True, help_text='WhatsApp Cloud API message ID for delivery tracking.', max_length=150, null=True, verbose_name='Meta message ID')),
                ('status', models.CharField(choices=[('pending_reply', 'Message Sent — Awaiting Reply'), ('confirmed', 'Customer Confirmed via WhatsApp'), ('cancelled', 'Customer Cancelled via WhatsApp'), ('timeout', 'No Response — Manual Call Required')], db_index=True, default='pending_reply', max_length=20, verbose_name='status')),
                ('customer_reply_text', models.CharField(blank=True, default='', max_length=100, verbose_name='customer reply text')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('notification', models.OneToOneField(blank=True, help_text='The Notification record that triggered this verification flow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_verification', to='notifications.notification', verbose_name='originating notification')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_cod_verification', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'WhatsApp COD verification',
                'verbose_name_plural': 'WhatsApp COD verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['channel', 'is_sent', 'created_at'], name='notificatio_channel_3636d4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'is_sent', 'created_at'], name='notificatio_notific_5ffa50_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_sent', 'created_at'], name='notificatio_is_sent_2262e4_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdeliveryattempt',
            index=models.Index(fields=['notification', 'attempted_at'], name='notificatio_notific_13b10a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdeliveryattempt',
            index=models.Index(fields=['outcome', 'attempted_at'], name='notificatio_outcome_04222f_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcodverification',
            index=models.Index(fields=['status', 'created_at'], name='notificatio_status_23614e_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcodverification',
            index=models.Index(fields=['phone_number', 'created_at'], name='notificatio_phone_n_5d3f87_idx'),
        ),
    ]
