# Generated by Django 6.0.6 on 2026-07-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('cod_verification', 'COD Order Verification'), ('order_placed', 'Order Placed'), ('order_shipped', 'Order Shipped (AWB Attached)'), ('out_for_delivery', 'Rider Out For Delivery'), ('promotional', 'Marketing / Discount Alert'), ('system_alert', 'System / Security Alert'), ('order_delivered', 'Order Delivered Successfully'), ('rto_alert', 'RTO — Parcel Returned to Warehouse')], max_length=30, verbose_name='notification type'),
        ),
    ]
