# Generated by Django 6.0.6 on 2026-07-14 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_unique_together'),
        ('coupons', '0001_initial'),
        ('products', '0003_lowstockalert_productspecification_stockreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_carts', to='coupons.coupon', verbose_name='applied coupon'),
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon_code_input',
            field=models.CharField(blank=True, default='', help_text='Last coupon code entered — preserved for display even if coupon expires between sessions.', max_length=50, verbose_name='coupon code input'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['updated_at'], name='cart_cart_updated_c46eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['product', 'cart'], name='cart_cartit_product_0f9984_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='unique_product_per_cart'),
        ),
    ]
