# Generated by Django 6.0.6 on 2026-07-14 11:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_lowstockalert_productspecification_stockreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_type', models.CharField(choices=[('standard', 'Standard Rate GST'), ('zero_rated', 'Zero Rated'), ('exempt', 'GST Exempt')], default='standard', max_length=15, verbose_name='tax type')),
                ('rate_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GST percentage. e.g. 17.00 for standard GST.', max_digits=5, verbose_name='rate (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('effective_from', models.DateField(help_text='Date from which this rate is applicable.', verbose_name='effective from')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_rates', to='products.category', verbose_name='product category')),
            ],
            options={
                'verbose_name': 'tax rate',
                'verbose_name_plural': 'tax rates',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['category', '-effective_from'], name='tax_taxrate_categor_40362e_idx')],
            },
        ),
    ]
