# Generated by Django 6.0.6 on 2026-07-14 11:47

import apps.orders.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('products', '0003_lowstockalert_productspecification_stockreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(db_index=True, default=apps.orders.models._generate_order_number, max_length=30, unique=True, verbose_name='order number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='order status')),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment'), ('bank_transfer', 'Bank Transfer')], max_length=20, verbose_name='payment method')),
                ('notes', models.TextField(blank=True, default='', verbose_name='customer delivery notes')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Sum of all OrderItem subtotals before discount.', max_digits=10, verbose_name='subtotal')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='shipping fee')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total coupon discount applied — PKR amount.', max_digits=10, verbose_name='discount amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all OrderItem tax amounts.', max_digits=10, verbose_name='total tax amount')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='subtotal - discount_amount + shipping_fee + tax_amount', max_digits=10, verbose_name='total price')),
                ('coupon_code_snapshot', models.CharField(blank=True, default='', help_text='Coupon code at time of order — preserved even if coupon is later deleted. Used on invoice and order history.', max_length=50, verbose_name='coupon code snapshot')),
                ('placed_at', models.DateTimeField(auto_now_add=True, verbose_name='placed at')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processing started at')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='shipped at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='refunded at')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='coupons.coupon', verbose_name='coupon applied')),
                ('user', models.ForeignKey(help_text='PROTECT — financial records must survive user deactivation.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=255, verbose_name='product name')),
                ('product_sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Product.price at order time — before any discount.', max_digits=10, verbose_name='original price')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Product.current_price at order time — after product discount.', max_digits=10, verbose_name='unit price paid')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='unit_price × quantity — auto-calculated.', max_digits=10, verbose_name='subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='(original_price - unit_price) × quantity. Shows customer their per-item saving on invoice.', max_digits=10, verbose_name='item discount amount')),
                ('tax_rate_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GST/tax rate snapshotted at order time.', max_digits=5, verbose_name='tax rate (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='subtotal × tax_rate / 100 — auto-calculated.', max_digits=10, verbose_name='tax amount (PKR)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='order')),
                ('product', models.ForeignKey(help_text='PROTECT — product cannot be deleted while referenced in order history.', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Pakistani phone number. Format: +923001234567 or 03001234567', regex='^\\+?92\\d{10}$|^0\\d{10}$')], verbose_name='phone number')),
                ('address_line1', models.CharField(max_length=255, verbose_name='address line 1')),
                ('address_line2', models.CharField(blank=True, default='', max_length=255, verbose_name='address line 2')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('province', models.CharField(max_length=2, verbose_name='province')),
                ('postal_code', models.CharField(max_length=10, verbose_name='postal code')),
                ('country', models.CharField(default='Pakistan', editable=False, max_length=100, verbose_name='country')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'order shipping address',
                'verbose_name_plural': 'order shipping addresses',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20, verbose_name='previous status')),
                ('to_status', models.CharField(max_length=20, verbose_name='new status')),
                ('note', models.TextField(blank=True, default='', verbose_name='internal note')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='logged at')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Null = system-initiated transition (e.g. Celery task).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'order status log',
                'verbose_name_plural': 'order status logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'placed_at'], name='orders_orde_status_883c98_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method', 'status'], name='orders_orde_payment_e02dad_idx'),
        ),
        
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product', 'created_at'], name='orders_orde_product_9a366c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='orders_orde_order_i_52f79a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatuslog',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_93aa9f_idx'),
        ),
    ]
