from decimal import Decimal
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.translation import gettext_lazy as _
from apps.common.models import TimeStampedModel
from apps.logistics.models import CourierPartner



class DailySalesSnapshot(TimeStampedModel):
    """
    Aggregated daily metrics generated by nightly cron/Celery jobs.
    Prevents analytical queries from locking live production order tables.
    """
    date = models.DateField(unique=True, db_index=True)
    
    total_orders = models.PositiveIntegerField(default=0)
    total_gmv_pkr = models.DecimalField(max_digits=14, decimal_places=2, default=Decimal('0.00'), help_text=_("Gross Merchandise Value"))
    net_revenue_pkr = models.DecimalField(max_digits=14, decimal_places=2, default=Decimal('0.00'))
    
    # Payment Method Breakdown
    cod_orders_count = models.PositiveIntegerField(default=0)
    prepaid_orders_count = models.PositiveIntegerField(default=0)
    
    # Discount Metrics
    total_discount_given_pkr = models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0.00'))
    
    # Logistics Metrics
    rto_orders_count = models.PositiveIntegerField(default=0, help_text=_("Orders returned to origin on this date"))
    rto_losses_pkr = models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0.00'), help_text=_("Wasted shipping fees due to RTO"))

    class Meta:
        verbose_name = _("Daily Sales Snapshot")
        verbose_name_plural = _("Daily Sales Snapshots")
        ordering = ['-date']

    def __str__(self):
        return f"Snapshot for {self.date} (GMV: {self.total_gmv_pkr} PKR)"


class CourierPerformanceMetric(TimeStampedModel):
    """
    Tracks logistics efficiency to dynamically assign couriers (e.g., routing Lahore orders
    to Trax and rural Sindh orders to TCS based on historical success rates).
    """
    courier = models.CharField(max_length=20, choices=CourierPartner.choices)
    city = models.CharField(max_length=100, db_index=True)
    month_year = models.CharField(max_length=7, help_text=_("Format: YYYY-MM, e.g., '2026-07'"))
    
    total_assigned = models.PositiveIntegerField(default=0)
    delivered_successfully = models.PositiveIntegerField(default=0)
    rto_count = models.PositiveIntegerField(default=0)
    avg_delivery_time_hours = models.DecimalField(max_digits=6, decimal_places=2, default=Decimal('0.00'))

    class Meta:
        verbose_name = _("Courier Performance Metric")
        verbose_name_plural = _("Courier Performance Metrics")
        unique_together = ('courier', 'city', 'month_year')
        indexes = [
            models.Index(fields=['city', 'courier']),
        ]

    @property
    def delivery_success_rate(self) -> float:
        if self.total_assigned == 0:
            return 0.0
        return round((self.delivered_successfully / self.total_assigned) * 100, 2)