# apps/analytics/models.py
from __future__ import annotations
from decimal import Decimal
import logging

from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.common.models import TimeStampedModel
from apps.logistics.models import CourierPartner

logger = logging.getLogger("apps.analytics")


class DailySalesSnapshot(TimeStampedModel):
    """
    Aggregated daily metrics — generated by nightly Celery task.

    Prevents analytical queries from hitting live order tables.
    All fields are INSERT-time snapshots — never recomputed after creation.
    If regeneration needed: delete row and re-run Celery task for that date.
    """

    date = models.DateField(
        _("date"),
        unique=True,
        db_index=True,
    )
    total_orders = models.PositiveIntegerField(
        _("total orders"),
        default=0,
    )
    cancelled_orders_count = models.PositiveIntegerField(
        _("cancelled orders count"),
        default=0,
    )
    refunded_orders_count = models.PositiveIntegerField(
        _("refunded orders count"),
        default=0,
    )
    total_gmv_pkr = models.DecimalField(
        _("gross merchandise value (PKR)"),
        max_digits=14,
        decimal_places=2,
        default=Decimal("0.00"),
        help_text=_("Total order value before returns and cancellations."),
    )
    net_revenue_pkr = models.DecimalField(
        _("net revenue (PKR)"),
        max_digits=14,
        decimal_places=2,
        default=Decimal("0.00"),
        help_text=_("GMV minus refunds and discounts."),
    )
    avg_order_value_pkr = models.DecimalField(
        _("average order value (PKR)"),
        max_digits=10,
        decimal_places=2,
        default=Decimal("0.00"),
    )
    cod_orders_count = models.PositiveIntegerField(
        _("COD orders count"),
        default=0,
    )
    prepaid_orders_count = models.PositiveIntegerField(
        _("prepaid orders count"),
        default=0,
    )
    total_discount_given_pkr = models.DecimalField(
        _("total discount given (PKR)"),
        max_digits=12,
        decimal_places=2,
        default=Decimal("0.00"),
    )
    rto_orders_count = models.PositiveIntegerField(
        _("RTO orders count"),
        default=0,
        help_text=_("Orders returned to origin on this date."),
    )
    rto_losses_pkr = models.DecimalField(
        _("RTO losses (PKR)"),
        max_digits=12,
        decimal_places=2,
        default=Decimal("0.00"),
        help_text=_("Wasted shipping fees due to RTO."),
    )

    class Meta:
        verbose_name        = _("daily sales snapshot")
        verbose_name_plural = _("daily sales snapshots")
        ordering            = ["-date"]

    def __str__(self) -> str:
        return f"Snapshot {self.date} — GMV: Rs. {self.total_gmv_pkr}"


class CourierPerformanceMetric(TimeStampedModel):
    """
    Monthly per-city performance metrics per courier.

    Used by smart courier routing to select best courier per city.
    Generated by Celery task on first day of each month.
    """

    courier = models.CharField(
        _("courier partner"),
        max_length=20,
        choices=CourierPartner.choices,
    )
    city = models.CharField(
        _("city"),
        max_length=100,
        db_index=True,
    )
    month_year = models.DateField(
        _("month"),
        db_index=True,
        help_text=_(
            "First day of the month this metric covers. "
            "e.g. 2026-07-01 represents July 2026."
        ),
    )
    total_assigned = models.PositiveIntegerField(
        _("total assigned"),
        default=0,
    )
    delivered_successfully = models.PositiveIntegerField(
        _("delivered successfully"),
        default=0,
    )
    rto_count = models.PositiveIntegerField(
        _("RTO count"),
        default=0,
    )
    avg_delivery_time_hours = models.DecimalField(
        _("average delivery time (hours)"),
        max_digits=6,
        decimal_places=2,
        default=Decimal("0.00"),
    )

    class Meta:
        verbose_name        = _("courier performance metric")
        verbose_name_plural = _("courier performance metrics")
        ordering            = ["-month_year"]
        constraints = [
            models.UniqueConstraint(
                fields=["courier", "city", "month_year"],
                name="unique_courier_city_month",
            )
        ]
        indexes = [
            models.Index(fields=["city",    "courier"]),
            models.Index(fields=["courier", "month_year"]),
        ]

    @property
    def delivery_success_rate(self) -> float:
        if self.total_assigned == 0:
            return 0.0
        return round(
            (self.delivered_successfully / self.total_assigned) * 100, 2
        )

    def __str__(self) -> str:
        return (
            f"{self.get_courier_display()} — {self.city} — "
            f"{self.month_year.strftime('%Y-%m')} "
            f"({self.delivery_success_rate}% success)"
        )
# from decimal import Decimal
# from django.db import models
# from django.conf import settings
# from django.core.validators import MinValueValidator, MaxValueValidator
# from django.utils.translation import gettext_lazy as _
# from apps.common.models import TimeStampedModel
# from apps.logistics.models import CourierPartner



# class DailySalesSnapshot(TimeStampedModel):
#     """
#     Aggregated daily metrics generated by nightly cron/Celery jobs.
#     Prevents analytical queries from locking live production order tables.
#     """
#     date = models.DateField(unique=True, db_index=True)
    
#     total_orders = models.PositiveIntegerField(default=0)
#     total_gmv_pkr = models.DecimalField(max_digits=14, decimal_places=2, default=Decimal('0.00'), help_text=_("Gross Merchandise Value"))
#     net_revenue_pkr = models.DecimalField(max_digits=14, decimal_places=2, default=Decimal('0.00'))
    
#     # Payment Method Breakdown
#     cod_orders_count = models.PositiveIntegerField(default=0)
#     prepaid_orders_count = models.PositiveIntegerField(default=0)
    
#     # Discount Metrics
#     total_discount_given_pkr = models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0.00'))
    
#     # Logistics Metrics
#     rto_orders_count = models.PositiveIntegerField(default=0, help_text=_("Orders returned to origin on this date"))
#     rto_losses_pkr = models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0.00'), help_text=_("Wasted shipping fees due to RTO"))

#     class Meta:
#         verbose_name = _("Daily Sales Snapshot")
#         verbose_name_plural = _("Daily Sales Snapshots")
#         ordering = ['-date']

#     def __str__(self):
#         return f"Snapshot for {self.date} (GMV: {self.total_gmv_pkr} PKR)"


# class CourierPerformanceMetric(TimeStampedModel):
#     """
#     Tracks logistics efficiency to dynamically assign couriers (e.g., routing Lahore orders
#     to Trax and rural Sindh orders to TCS based on historical success rates).
#     """
#     courier = models.CharField(max_length=20, choices=CourierPartner.choices)
#     city = models.CharField(max_length=100, db_index=True)
#     month_year = models.CharField(max_length=7, help_text=_("Format: YYYY-MM, e.g., '2026-07'"))
    
#     total_assigned = models.PositiveIntegerField(default=0)
#     delivered_successfully = models.PositiveIntegerField(default=0)
#     rto_count = models.PositiveIntegerField(default=0)
#     avg_delivery_time_hours = models.DecimalField(max_digits=6, decimal_places=2, default=Decimal('0.00'))

#     class Meta:
#         verbose_name = _("Courier Performance Metric")
#         verbose_name_plural = _("Courier Performance Metrics")
#         unique_together = ('courier', 'city', 'month_year')
#         indexes = [
#             models.Index(fields=['city', 'courier']),
#         ]

#     @property
#     def delivery_success_rate(self) -> float:
#         if self.total_assigned == 0:
#             return 0.0
#         return round((self.delivered_successfully / self.total_assigned) * 100, 2)