# Generated by Django 6.0.6 on 2026-07-07 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_updated_at_and_indexes_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('other', 'Other')], default='home', max_length=10, verbose_name='address label')),
                ('address_line1', models.CharField(help_text='Street address, house number, building name.', max_length=255, verbose_name='address line 1')),
                ('address_line2', models.CharField(blank=True, default='', help_text='Apartment, floor, area, landmark. Optional.', max_length=255, verbose_name='address line 2')),
                ('city', models.CharField(choices=[('Lahore', 'Lahore'), ('Faisalabad', 'Faisalabad'), ('Rawalpindi', 'Rawalpindi'), ('Gujranwala', 'Gujranwala'), ('Multan', 'Multan'), ('Sialkot', 'Sialkot'), ('Bahawalpur', 'Bahawalpur'), ('Sargodha', 'Sargodha'), ('Sheikhupura', 'Sheikhupura'), ('Gujrat', 'Gujrat'), ('Rahim Yar Khan', 'Rahim Yar Khan'), ('Jhang', 'Jhang'), ('Sahiwal', 'Sahiwal'), ('Okara', 'Okara'), ('Kasur', 'Kasur'), ('Karachi', 'Karachi'), ('Hyderabad', 'Hyderabad'), ('Sukkur', 'Sukkur'), ('Larkana', 'Larkana'), ('Nawabshah', 'Nawabshah'), ('Mirpur Khas', 'Mirpur Khas'), ('Peshawar', 'Peshawar'), ('Abbottabad', 'Abbottabad'), ('Mardan', 'Mardan'), ('Swat', 'Swat'), ('Kohat', 'Kohat'), ('Mingora', 'Mingora'), ('Quetta', 'Quetta'), ('Turbat', 'Turbat'), ('Khuzdar', 'Khuzdar'), ('Islamabad', 'Islamabad'), ('Muzaffarabad', 'Muzaffarabad'), ('Gilgit', 'Gilgit')], help_text='Select your city from the list.', max_length=50, verbose_name='city')),
                ('province', models.CharField(choices=[('PB', 'Punjab'), ('SD', 'Sindh'), ('KP', 'Khyber Pakhtunkhwa'), ('BL', 'Balochistan'), ('GB', 'Gilgit-Baltistan'), ('AK', 'Azad Jammu & Kashmir'), ('IC', 'Islamabad Capital Territory')], editable=False, help_text='Auto-derived from selected city.', max_length=2, verbose_name='province')),
                ('postal_code', models.CharField(editable=False, help_text='Auto-derived from selected city.', max_length=10, verbose_name='postal code')),
                ('country', models.CharField(default='Pakistan', editable=False, max_length=100, verbose_name='country')),
                ('is_default', models.BooleanField(default=False, help_text='Only one address per user can be default.', verbose_name='is default')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user address',
                'verbose_name_plural': 'user addresses',
                'ordering': ['-is_default', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_address_per_user')],
            },
        ),
    ]
