# Generated by Django 6.0.6 on 2026-07-08 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_address_fields_from_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='Pakistani phone number. Format: +923001234567 or 03001234567. Must be unique across all accounts.', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Pakistani phone number. Format: +923001234567 or 03001234567', regex='^\\+?92\\d{10}$|^0\\d{10}$')], verbose_name='phone number'),
        ),
    ]
