# Generated by Django 6.0.6 on 2026-07-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_phone_unique_and_indexed_on_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Token is marked used immediately after successful verification. Used tokens are rejected even if they have not yet expired.', verbose_name='is used'),
        ),
    ]
