# Generated by Django 6.0.6 on 2026-07-08 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_is_used_to_emailverificationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_attempted', models.EmailField(help_text='Email submitted in the login form. Stored separately from user FK — captures attempts against non-existent accounts too.', max_length=254, verbose_name='email attempted')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Remote IP of the login request.', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, default='', help_text='Browser and device string from request headers.', verbose_name='user agent')),
                ('was_successful', models.BooleanField(help_text='True if credentials were valid and user logged in.', verbose_name='was successful')),
                ('failure_reason', models.CharField(blank=True, default='', help_text='Short code for failed attempts. e.g. invalid_credentials, account_inactive, email_not_verified', max_length=50, verbose_name='failure reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('user', models.ForeignKey(blank=True, help_text='SET NULL on delete — preserve security logs even if user account is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_activity', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user login activity',
                'verbose_name_plural': 'user login activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='acc_user_created_idx'), models.Index(fields=['ip_address', 'created_at'], name='acc_ip_created_idx'), models.Index(fields=['was_successful', 'created_at'], name='acc_success_created_idx')],
            },
        ),
    ]
