# Generated by Django 6.0.6 on 2026-07-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_userloginactivity_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_phone_verified',
            field=models.BooleanField(default=False, help_text='True after customer confirms phone via WhatsApp COD verification. Verified customers skip re-verification on subsequent COD orders.', verbose_name='phone verified'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='phone verified at'),
        ),
    ]
