# Generated by Django 6.0.6 on 2026-07-13 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_phone_verification_fields_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Phone number for delivery at this address. Leave blank to use profile phone number.', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Pakistani phone number. Format: +923001234567 or 03001234567', regex='^\\+?92\\d{10}$|^0\\d{10}$')], verbose_name='contact phone for this address'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'is_default'], name='accounts_us_user_id_7fa4e4_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'created_at'], name='accounts_us_user_id_ae5194_idx'),
        ),
    ]
