# Generated by Django 6.0.6 on 2026-07-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_create_pending_email_change_table'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userloginactivity',
            index=models.Index(fields=['ip_address', 'was_successful', 'created_at'], name='acc_ip_fail_rate_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginactivity',
            index=models.Index(fields=['email_attempted', 'was_successful', 'created_at'], name='acc_email_fail_rate_idx'),
        ),
    ]
