# Generated by Django 6.0.6 on 2026-07-19 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('apple', 'Apple')], max_length=20, verbose_name='provider')),
                ('provider_id', models.CharField(max_length=255, verbose_name='provider user ID')),
                ('provider_email', models.EmailField(max_length=254, verbose_name='provider email')),
                ('is_provider_email_verified', models.BooleanField(default=False, help_text='True if the OAuth provider confirmed ownership of the email at login.', verbose_name='provider email verified')),
                ('avatar_url', models.URLField(blank=True, default='', max_length=2048, verbose_name='avatar URL')),
                ('access_token', models.TextField(blank=True, default='', verbose_name='access token')),
                ('refresh_token', models.TextField(blank=True, default='', verbose_name='refresh token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='token expires at')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Raw OAuth profile payload returned by the provider for auditing and debugging.', verbose_name='extra data')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='last login at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'social account',
                'verbose_name_plural': 'social accounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider'], name='accounts_social_provider_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_id'), name='unique_provider_identity'), models.UniqueConstraint(fields=('user', 'provider'), name='unique_provider_per_user')],
            },
        ),
    ]
