# Generated by Django 6.0.6 on 2026-07-20 10:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_socialaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityVerifiedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('change_email', 'Change Email'), ('change_password', 'Change Password'), ('delete_account', 'Delete Account')], max_length=20, verbose_name='purpose')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token')),
                ('is_used', models.BooleanField(default=False, verbose_name='is used')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Carried over from SecurityVerificationOTP metadata.', verbose_name='metadata')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_verified_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'security verified session',
                'verbose_name_plural': 'security verified sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('change_email', 'Change Email'), ('change_password', 'Change Password'), ('delete_account', 'Delete Account')], max_length=20, verbose_name='purpose')),
                ('otp_hash', models.CharField(max_length=128, verbose_name='OTP hash')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts')),
                ('is_used', models.BooleanField(default=False, verbose_name='is used')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Contextual data like {'new_email': 'foo@bar.com'} bound to this OTP.", verbose_name='metadata')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_otps', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'security verification OTP',
                'verbose_name_plural': 'security verification OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'is_used'], name='accounts_otp_lookup_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_used', False)), fields=('user', 'purpose'), name='unique_active_otp_per_user_purpose')],
            },
        ),
    ]
