# Generated by Django 6.0.6 on 2026-07-20 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_securityverifiedsession_securityverificationotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingemailchange',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 20, 11, 45, 36, 694498, tzinfo=datetime.timezone.utc), help_text='Overall request window. 24 hours from creation.', verbose_name=' expires at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='securityverificationotp',
            name='purpose',
            field=models.CharField(choices=[('change_email', 'Change Email'), ('change_password', 'Change Password'), ('delete_account', 'Delete Account'), ('verify_new_email', 'Verify New Email')], max_length=20, verbose_name='purpose'),
        ),
        migrations.AlterField(
            model_name='securityverifiedsession',
            name='purpose',
            field=models.CharField(choices=[('change_email', 'Change Email'), ('change_password', 'Change Password'), ('delete_account', 'Delete Account'), ('verify_new_email', 'Verify New Email')], max_length=20, verbose_name='purpose'),
        ),
    ]
