# Generated by Django 6.0.6 on 2026-07-14 11:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0003_lowstockalert_productspecification_stockreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='title')),
                ('body', models.TextField(blank=True, default='', verbose_name='body')),
                ('is_approved', models.BooleanField(default=False, help_text='Review shown to customers only after approval. Moderation history tracked in ReviewModerationLog.', verbose_name='approved')),
                ('order_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='orders.orderitem', verbose_name='verified purchase item')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='products.product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='reviewer')),
            ],
            options={
                'verbose_name': 'customer review',
                'verbose_name_plural': 'customer reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Re-review')], max_length=10, verbose_name='action')),
                ('reason', models.TextField(blank=True, default='', help_text='Required when action is REJECTED or FLAGGED.', verbose_name='reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='actioned at')),
                ('moderated_by', models.ForeignKey(blank=True, help_text='Null means system-automated moderation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='moderated by')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='reviews.review', verbose_name='review')),
            ],
            options={
                'verbose_name': 'review moderation log',
                'verbose_name_plural': 'review moderation logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vote', models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful')], max_length=15, verbose_name='vote')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reviews.review', verbose_name='review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL, verbose_name='voter')),
            ],
            options={
                'verbose_name': 'review vote',
                'verbose_name_plural': 'review votes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'is_approved'], name='reviews_rev_product_99e47c_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'created_at'], name='reviews_rev_user_id_35ef9b_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='reviews_rev_rating_2db6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewmoderationlog',
            index=models.Index(fields=['review', 'created_at'], name='reviews_rev_review__01342d_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewmoderationlog',
            index=models.Index(fields=['moderated_by', 'created_at'], name='reviews_rev_moderat_ab4c3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewvote',
            unique_together={('review', 'user')},
        ),
    ]
