# Generated by Django 6.0.6 on 2026-07-14 12:33

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.CharField(choices=[('cod', 'Cash on Delivery'), ('safepay', 'Safepay'), ('payfast', 'PayFast'), ('jazzcash', 'JazzCash Mobile Wallet / Card'), ('easypaisa', 'Easypaisa'), ('raast', 'Raast Instant Transfer'), ('xpay', 'XPay by PostEx')], default='cod', max_length=20, verbose_name='payment gateway')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], db_index=True, default='pending', max_length=30, verbose_name='status')),
                ('amount_pkr', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='amount (PKR)')),
                ('transaction_reference', models.CharField(blank=True, help_text='Gateway-assigned transaction ID. Null until gateway responds.', max_length=150, null=True, unique=True, verbose_name='transaction reference')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Auto-generated. Passed to gateway on payment initiation. Prevents double-charging on network retries.', unique=True, verbose_name='idempotency key')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='orders.order', verbose_name='order')),
                ('user', models.ForeignKey(blank=True, help_text='SET_NULL — payment audit survives user deletion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
            options={
                'verbose_name': 'payment transaction',
                'verbose_name_plural': 'payment transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_pkr', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='refund amount (PKR)')),
                ('reason', models.CharField(choices=[('customer_request', 'Customer Request'), ('out_of_stock', 'Item Out of Stock'), ('damaged_item', 'Damaged Item Received'), ('wrong_item', 'Wrong Item Delivered'), ('other', 'Other')], default='other', max_length=20, verbose_name='reason')),
                ('reason_detail', models.TextField(blank=True, default='', verbose_name='reason detail')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='initiated', max_length=20, verbose_name='refund status')),
                ('gateway_refund_reference', models.CharField(blank=True, default='', help_text='Reference ID returned by payment gateway for this refund.', max_length=150, verbose_name='gateway refund reference')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Auto-set when status transitions to COMPLETED.', null=True, verbose_name='completed at')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_refunds', to=settings.AUTH_USER_MODEL, verbose_name='initiated by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='orders.order', verbose_name='order')),
                ('original_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.paymenttransaction', verbose_name='original transaction')),
            ],
            options={
                'verbose_name': 'refund transaction',
                'verbose_name_plural': 'refund transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.CharField(db_index=True, max_length=50, verbose_name='gateway')),
                ('payload', models.JSONField(help_text='Raw JSON payload received from gateway. Immutable.', verbose_name='payload')),
                ('headers', models.JSONField(help_text='HTTP request headers — used for HMAC signature verification. Immutable.', verbose_name='headers')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('is_verified', models.BooleanField(default=False, help_text='True if HMAC signature matched gateway secret.', verbose_name='signature verified')),
                ('processed_successfully', models.BooleanField(default=False, verbose_name='processed successfully')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('exception_trace', models.TextField(blank=True, default='', verbose_name='exception trace')),
                ('payment_transaction', models.ForeignKey(blank=True, help_text='Linked after webhook is matched to a transaction. Null for unrecognized or fraudulent webhooks.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='payments.paymenttransaction', verbose_name='payment transaction')),
            ],
            options={
                'verbose_name': 'webhook log',
                'verbose_name_plural': 'webhook logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['order', 'status'], name='payments_pa_order_i_ed562a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['gateway', 'status'], name='payments_pa_gateway_186290_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_c4e513_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['gateway', 'status', 'created_at'], name='payment_gateway_status_idx'),
        ),
        migrations.AddIndex(
            model_name='refundtransaction',
            index=models.Index(fields=['order', 'status'], name='payments_re_order_i_817983_idx'),
        ),
        migrations.AddIndex(
            model_name='refundtransaction',
            index=models.Index(fields=['status', 'created_at'], name='payments_re_status_43cd2d_idx'),
        ),
        migrations.AddIndex(
            model_name='refundtransaction',
            index=models.Index(fields=['original_transaction', 'status'], name='payment_refund_txn_status_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['gateway', 'created_at'], name='payments_we_gateway_7044b5_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['is_verified', 'processed_successfully'], name='payments_we_is_veri_488796_idx'),
        ),
    ]
