# Generated by Django 6.0.6 on 2026-07-14 11:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='e.g. EIDMUBARAK2026 — always stored uppercase.', max_length=50, unique=True, verbose_name='code')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed_pkr', 'Fixed Amount (PKR)'), ('free_shipping', 'Free Shipping')], default='fixed_pkr', max_length=20, verbose_name='discount type')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='PKR amount for FIXED_PKR. Percentage (0–100) for PERCENTAGE. Must be 0 for FREE_SHIPPING.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='discount value')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum cart subtotal in PKR to apply coupon.', max_digits=10, verbose_name='minimum order amount')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap on discount in PKR — only applies to PERCENTAGE type.', max_digits=10, null=True, verbose_name='maximum discount amount')),
                ('usage_limit_total', models.PositiveIntegerField(blank=True, help_text='Maximum global uses. Null = unlimited.', null=True, verbose_name='total usage limit')),
                ('usage_limit_per_user', models.PositiveSmallIntegerField(default=1, help_text='Maximum times one user can use this coupon.', verbose_name='per user usage limit')),
                ('valid_from', models.DateTimeField(verbose_name='valid from')),
                ('valid_until', models.DateTimeField(verbose_name='valid until')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('times_used', models.PositiveIntegerField(db_index=True, default=0, help_text='Fast pre-check counter for Phase 1 validation. Incremented atomically via F() expressions at checkout commit. Decremented on order cancellation. May temporarily diverge — authoritative check uses CouponUsage.count() inside the checkout service transaction.', verbose_name='times used')),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'is_active', 'valid_until'], name='coupons_cou_code_8b18b7_idx'), models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='coupons_cou_is_acti_1d54f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_applied', models.DecimalField(decimal_places=2, help_text='Actual PKR amount discounted on this order.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='discount applied')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='coupons.coupon', verbose_name='coupon')),
            ],
            options={
                'verbose_name': 'coupon usage',
                'verbose_name_plural': 'coupon usages',
                'ordering': ['-created_at'],
            },
        ),
    ]
