# Generated by Django 6.0.6 on 2026-07-14 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bikemodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Admin alert triggered when stock falls to or below this number. Set to 0 to disable alerts for this product.', verbose_name='low stock threshold'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, help_text='Product weight for shipping cost calculation. Also add as ProductSpecification for display on product page.', null=True, verbose_name='weight (grams)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='products.category', verbose_name='parent category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'status'], name='products_pr_brand_i_6bc83e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'status'], name='products_pr_is_feat_bd97b9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock', 'status'], name='products_pr_stock_df9f47_idx'),
        ),
        migrations.AddConstraint(
            model_name='bikemodel',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='unique_bike_model_per_brand'),
        ),
    ]
