# Generated by Django 6.0.6 on 2026-07-14 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_bikemodel_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LowStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_at_alert', models.PositiveIntegerField(help_text='Product.stock value when alert was triggered.', verbose_name='stock at alert time')),
                ('threshold_at_alert', models.PositiveIntegerField(help_text='Product.low_stock_threshold when alert was triggered. Snapshotted in case threshold is later changed.', verbose_name='threshold at alert time')),
                ('is_resolved', models.BooleanField(default=False, help_text='Mark True after restocking product.', verbose_name='resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_alerts', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'low stock alert',
                'verbose_name_plural': 'low stock alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'is_resolved'], name='products_lo_product_6b74c7_idx'), models.Index(fields=['is_resolved', 'created_at'], name='products_lo_is_reso_0cd335_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Material, Weight, Thread Size, Position', max_length=100, verbose_name='specification name')),
                ('value', models.CharField(help_text='e.g. OEM Steel, 250g, M20×1.5, Front', max_length=255, verbose_name='specification value')),
                ('unit', models.CharField(blank=True, default='', help_text='Optional unit e.g. mm, kg, g. Leave blank if value already includes unit.', max_length=20, verbose_name='unit')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Controls order specs appear on product page.', verbose_name='display order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product specification',
                'verbose_name_plural': 'product specifications',
                'ordering': ['display_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('product', 'name'), name='unique_spec_name_per_product')],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, db_index=True, default='', help_text='Fallback identifier if user logs out mid-checkout.', max_length=40, verbose_name='session key')),
                ('quantity', models.PositiveIntegerField(verbose_name='reserved quantity')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='products.product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'stock reservation',
                'verbose_name_plural': 'stock reservations',
                'indexes': [models.Index(fields=['product', 'expires_at'], name='products_st_product_db2e26_idx'), models.Index(fields=['user', 'expires_at'], name='products_st_user_id_566bcc_idx'), models.Index(fields=['expires_at'], name='products_st_expires_817182_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'user'), name='unique_reservation_per_user_product')],
            },
        ),
    ]
